# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib_sequence = [1, 2]
evens = [2]
limit = 4000000
exceeding_limit = False

while exceeding_limit == False:
    num = fib_sequence[-1] + fib_sequence[-2]
    if num > limit:
        exceeding_limit = True
    else:
        fib_sequence.append(num)
        if num % 2 == 0:
            evens.append(num)

print(sum(evens))


